/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PausaParaElAlmaRouteImport } from './routes/pausa-para-el-alma'
import { Route as IndexRouteImport } from './routes/index'

const PausaParaElAlmaRoute = PausaParaElAlmaRouteImport.update({
  id: '/pausa-para-el-alma',
  path: '/pausa-para-el-alma',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pausa-para-el-alma': typeof PausaParaElAlmaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pausa-para-el-alma': typeof PausaParaElAlmaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pausa-para-el-alma': typeof PausaParaElAlmaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pausa-para-el-alma'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pausa-para-el-alma'
  id: '__root__' | '/' | '/pausa-para-el-alma'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PausaParaElAlmaRoute: typeof PausaParaElAlmaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pausa-para-el-alma': {
      id: '/pausa-para-el-alma'
      path: '/pausa-para-el-alma'
      fullPath: '/pausa-para-el-alma'
      preLoaderRoute: typeof PausaParaElAlmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PausaParaElAlmaRoute: PausaParaElAlmaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
