/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PausaParaElAlmaRouteImport } from './routes/pausa-para-el-alma'
import { Route as DescargablesRouteImport } from './routes/descargables'
import { Route as IndexRouteImport } from './routes/index'

const PausaParaElAlmaRoute = PausaParaElAlmaRouteImport.update({
  id: '/pausa-para-el-alma',
  path: '/pausa-para-el-alma',
  getParentRoute: () => rootRouteImport,
} as any)
const DescargablesRoute = DescargablesRouteImport.update({
  id: '/descargables',
  path: '/descargables',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/descargables': typeof DescargablesRoute
  '/pausa-para-el-alma': typeof PausaParaElAlmaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/descargables': typeof DescargablesRoute
  '/pausa-para-el-alma': typeof PausaParaElAlmaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/descargables': typeof DescargablesRoute
  '/pausa-para-el-alma': typeof PausaParaElAlmaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/descargables' | '/pausa-para-el-alma'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/descargables' | '/pausa-para-el-alma'
  id: '__root__' | '/' | '/descargables' | '/pausa-para-el-alma'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DescargablesRoute: typeof DescargablesRoute
  PausaParaElAlmaRoute: typeof PausaParaElAlmaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pausa-para-el-alma': {
      id: '/pausa-para-el-alma'
      path: '/pausa-para-el-alma'
      fullPath: '/pausa-para-el-alma'
      preLoaderRoute: typeof PausaParaElAlmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descargables': {
      id: '/descargables'
      path: '/descargables'
      fullPath: '/descargables'
      preLoaderRoute: typeof DescargablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DescargablesRoute: DescargablesRoute,
  PausaParaElAlmaRoute: PausaParaElAlmaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
